name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  DB_CONN_STRING: postgres://postegresql_user:5qAyjOua9On2iVIFotmsQYwYeIXTuC7y@dpg-ccrifqirrk08u0m08k60-a.oregon-postgres.render.com/postegresql?ssl=true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Initing CI
      run: npm ci
    - name: Testing
      run: npm test
